### PR TITLE
build(typing): add missing type hints

### PR DESCRIPTION
**Pull request by sisp**
Just some polishing :wink:: I've added a couple of missing type hints.

### CODE REVIEW

**Review by pawamoy — APPROVED** [review]
Nice!

Maybe you know that already: if you add `from __future__ import annotations` at the top of modules (to stringify annotations, lots to say on the subject, I invite anyone to read PEP 649 and related), and use Ruff to auto-fix the code, Ruff will automatically place imports that are only used for annotations under an `if TYPE_CHECKING:` condition.

**Comment by sisp** [comment]
We were briefly discussing about this topic a while ago without conclusion: https://github.com/copier-org/copier/pull/1179#discussion_r1230194072 What was [your point](https://github.com/copier-org/copier/pull/1179#discussion_r1231255519) about at the end, @yajo?

**Comment by pawamoy** [comment]
Ha, I followed my own advice and read PEP 649 more carefully (it improved a lot over time). Cyclic imports and `if TYPE_CHECKING` are still an ongoing problem in cases where annotations need to be resolved at runtime (Pydantic models, dataclasses). So it's not always possible to put imports under `if TYPE_CHECKING`, and I'm not sure how Ruff handles that.

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
> What was [your point](https://github.com/copier-org/copier/pull/1179#discussion_r1231255519)

I meant that, according to the docs, adding `from __future__ import annotations` will enable [PEP 563](https://peps.python.org/pep-0563/), but you were talking about [PEP 604](https://peps.python.org/pep-0604/) in that thread, which is only py3.10+.



> use Ruff to auto-fix the code

TIL about Ruff and looks promising. I'd be glad to use that in Copier!

**Pull request merged**
