### PR TITLE
docs(CONTRIBUTING.md): Add instructions on how to use Gitpod with a fork of the repo.

### PR DESCRIPTION
**Pull request by zathrath03**

### CODE REVIEW

**Comment by yajo** [comment]
This is actually not how it works. 

Instead, when you do your commit and push, gitpod will detect automatically that you don't have permissions and will assist you to create a fork, push there and open the PR.

Can you test that and update the docs please?

**Comment by zathrath03** [comment]
> This is actually not how it works.
> 
> Instead, when you do your commit and push, gitpod will detect automatically that you don't have permissions and will assist you to create a fork, push there and open the PR.
> 
> Can you test that and update the docs please?

I just tried and all I get is 
image
image

It doesn't give me any options to try to fork the repo.

I'm continuing to do some testing to see if I can figure out the best way to do this and will update CONTRIBUTING.md at that point.

**Comment by yajo** [comment]
> It doesn't give me any options to try to fork the repo.

That's weird. See how it works for me:

https://user-images.githubusercontent.com/973709/170991878-25e2c45d-4e52-496b-b29e-1be8aa338de6.mp4

**Comment by yajo** [comment]
Closing, as it seems stale.

**Pull request closed without merging**
