### PR TITLE
Better handle azdo style tags

### LINKED ISSUE #675: Copier 6.0.0 failing on Azure DevOps repo with Tags even with --vcs-ref=HEAD
**Describe the problem**
Attempting to run "copy" from an Azure DevOps repo with tags dies on parsing Git tags despite getting passed --vcs-ref=HEAD

**Template**
Can't share the template directly; however, setup a dummy repo that contains a tag similar to the tags that Azure DevOps creates

**To Reproduce**
1. Install copier 6.0.0
1. Run `copier --vcs-ref=HEAD copy git+https://github.com/mshafer-NI/copier-tag-bug-repro foo`
2. Answer "foo"

**Logs**

<details>

```
🎤 What do you want to call the thing you are building?
name? Format: str foo
Traceback (most recent call last):
  File "<python install dir>\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "<python install dir>\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "<copier venv dir>\.venv\Scripts\copier.exe\__main__.py", line 7, in <module>
  File "<copier venv dir>\.venv\lib\site-packages\plumbum\cli\application.py", line 629, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "<copier venv dir>\.venv\lib\site-packages\plumbum\cli\application.py", line 624, in run
    retcode = inst.main(*tailargs)
  File "<copier venv dir>\.venv\lib\site-packages\copier\cli.py", line 71, in _wrapper
    return method(*args, **kwargs)
  File "<copier venv dir>\.venv\lib\site-packages\copier\cli.py", line 297, in main
    cleanup_on_error=self.cleanup_on_error,
  File "<copier venv dir>\.venv\lib\site-packages\copier\main.py", line 601, in run_copy
    f"\nCopying from template version {self.template.version}",
  File "<copier venv dir>\.venv\lib\site-packages\backports\cached_property\__init__.py", line 80, in __get__
    val = self.func(instance)
  File "<copier venv dir>\.venv\lib\site-packages\copier\template.py", line 468, in version
    return Version(self.commit)
  File "<copier venv dir>\.venv\lib\site-packages\packaging\version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'test_tag.post23+deadbeef'
```

</details>

**Expected behavior**

Copier to not even attempt to parse tags if --vcs-ref=HEAD is passed

**Screenshots/screencasts/logs**

**Environment**
 - OS: Windows
 - Copier version: 6.0.0
 - Python version: 3.7.9
 - Installation method: pip

**Additional context**

### PR DESCRIPTION
**Pull request by mshafer-NI**
Fixes #675 

Create test with example tag (it fails), make the test pass - by checking one last time that we can parse a version out of the tag.

### CODE REVIEW

**Comment by mshafer-NI** [comment]
I have now verified that this fix makes it also pass the real-world case I was hitting.

**Comment by mshafer-NI** [comment]
@yajo, for some reason, I'm not seeing the option to request your review on this :(

**Comment by yajo** [comment]
Thanks, neat fix!

**Comment by mshafer-NI** [comment]
@yajo, do we want to release a 6.0.1 with this fix in it?

**Comment by yajo** [comment]
I still need to do some things before next release, but feel free to install from git master in the mean time.

**Pull request merged**
