### PR TITLE
Solve FieldValidationInfo warning

### LINKED ISSUE #1341: `FieldValidationInfo` is deprecated, use `ValidationInfo` instead.
### Describe the problem

Pydantic 2.4.0 emits the warning:

`FieldValidationInfo` is deprecated, use `ValidationInfo` instead.'

### Template

https://github.com/RomainBrault/python-whiteprint

### To Reproduce

_No response_

### Logs

```console
E       AssertionError: The CLI did not exit properly.
E       assert 1 == 0
E        +  where 1 = <Result DeprecationWarning('`FieldValidationInfo` is deprecated, use `ValidationInfo` instead.')>.exit_code`
```

### Expected behavior

No warning should be emited

### Screenshots/screencasts/logs

_No response_

### Operating system

Linux

### Operating system distribution and version

Ubuntu 23.04

### Copier version

8.3.0

### Python version

3.11.5

### Installation method

distro package

### Additional context

Conda install

The fix looks simple:

Replace FieldValidationInfo by FieldValidation in user_data.py

### PR DESCRIPTION
**Pull request by RomainBrault**
Fix #1341 by replacing FieldValidationInfo with ValidationInfo.

### CODE REVIEW

**Review by sisp — COMMENTED** [review]
The tests are failing because the `data` attribute was added to `ValidationInfo` in [`pydantic-core` v2.10.0](https://github.com/pydantic/pydantic-core/releases/tag/v2.10.0), and [Pydantic v2.3.0 uses `pydantic-core` v2.6.3](https://github.com/pydantic/pydantic/blob/v2.3.0/pyproject.toml#L64), which is the [currently locked version](https://github.com/copier-org/copier/blob/fe3b1aeb961ddea2f2e3587811ab98c42e888282/poetry.lock#L916-L933).

To make this work, we'd need to [bump Pydantic to `>=2.4.0` in `pyproject.toml`](https://github.com/copier-org/copier/blob/fe3b1aeb961ddea2f2e3587811ab98c42e888282/pyproject.toml#L39) and update the lock file. There's no other way as Pydantic pins the version of `pydantic-core`.

Since this would be a dependency version bump only because of an internal type hint, would the other @copier-org/maintainers be okay with this change?

**Comment by yajo** [comment]
Yes, please, do the bump, no problem with that. 😉

**Comment by sisp** [comment]
@RomainBrault You also need to update `poetry.lock`:

```sh
poetry update pydantic
```

**Review by yajo — APPROVED** [review]

**Review by sisp — CHANGES_REQUESTED** [review]
@yajo You upgraded the lock file with an old version of Poetry which reintroduced these `category = "..."` entries. This adds diff noise and the next Dependabot PR will remove them again.

**Comment by sisp** [comment]
FYI, I've fixed `pydantic-core` (https://github.com/pydantic/pydantic-core/pull/995), so the next Pydantic release that depends on the fixed `pydantic-core` version will work again.

**Comment by yajo** [comment]
Thanks! I updated it with a more modern poetry. I also updated the nix dev shell.

**Review by sisp — APPROVED** [review]
Perfect! :ok_hand:

**Pull request merged**
