### PR TITLE
build(isort): install with poetry

### PR DESCRIPTION
**Pull request by yajo**
pre-commit started failing with:

```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment

more info:

virtualenv python version did not match created version:
- actual version: 3.10.6.final.0
- expected version: 3.10.4.final.0
```

Quick fix while https://github.com/copier-org/copier/pull/696 gets on track.

Sadly I had to rollback https://github.com/copier-org/copier/pull/752 due to https://github.com/PyCQA/isort/issues/1945.

### CODE REVIEW

**Comment by sisp** [comment]
Yes, it's a an annoying situation with bad practices spreading in the Python ecosystem partly due to bad Poetry defaults . You found my issue over at the `isort` repo. 👍  I hope it gets resolved soon, but project activity has gone down there quite a bit. 😕

**Comment by yajo** [comment]
I see. Maybe the issue should be opened in poetry itself.

**Comment by sisp** [comment]
I haven't tried it, but would only capping `isort` to Python <4.0 work insteading of capping the Python version for the entire Copier project?

**Comment by yajo** [comment]
I just tried it and it doesn't work. Actually I discovered that https://github.com/copier-org/copier/pull/752 was buggy anyways due to questionary having the same problem.

**Comment by sisp** [comment]
Oh, I hadn't noticed that. Sorry. 🙇

**Comment by sisp** [comment]
I've created a PR over at `questionary` that removes the Python version upper bound: https://github.com/tmbo/questionary/pull/249

**Comment by sisp** [comment]
About raising the issue over at the Poetry project: https://github.com/python-poetry/poetry/discussions/3757 The Poetry maintainers seem to be resistant on this topic. :confused:

**Pull request merged**
