### PR TITLE
fix: require answer for questions without default value

### LINKED ISSUE #355: Mandatory answer and weird behavior with no default value
The documentation says: `default: Leave empty to force the user to answer.`

When not specifying the `default` key, the default value is `None`; perfect.  
But the prompt shows `🎤 [None]:`.  
I think it should be `🎤 :` maybe with above that `VAR_NAME? Required. Format: str`

When pressing enter, it should not accept an empty answer and should ask again (i.e. force the user to enter a value… as mandatory, and as described in the doc)

Currently, if pressing enter, that variable is `None` and using it in another default value "as a string", if becomes the string`"None"`… which is a known "problem" with Jinja (or Django templates at least).  
Wouldn't it be better to use an empty string `""` rather than `None`?

### PR DESCRIPTION
**Pull request by sisp**
I've fixed the behavior for questions without a default value when no answer is provided in the interactive questionnaire.

The new behavior is:

- `type: str` question: `""`
- `type: yaml` question: `None` (result of `yaml.safe_load("")`)
- `type: int`/`type: float`/`type: json` question: Validation error `Invalid input`
- `type: bool` question: `False` (implicit default)
- `choice: ...` question: The first choice (implicit default).

I think this new behavior is more intuitive and expected than the current one.

Fixes #355 #956.

Note: This PR does not change the behavior when the `--default` flag is passed because it is not yet clear how to deal with questions that lead to a validation error when no default value exists.

### CODE REVIEW

**Comment by yajo** [comment]
For int and float, the default could be 0. And for Json, null. If we do it like that, we avoid the errors. What do you think?

**Comment by sisp** [comment]
After giving this some more thought and reading https://github.com/copier-org/copier/issues/355#issuecomment-1019069511 again, I think whether the correct/consistent solution is this:

The `--defaults` flag (or equivalent argument via API) can only be used when the `default` field is set for *all* questions. Otherwise, an error is raised. Questions without a `default` field are required and must be answered either interactively or via the `--data` flag (or equivalent argument via API). In interactive mode, there are some implicit initial values/selections:

* `str` question: `""` because this is the best initial value for the input prompt.
* `bool` question: `False` because [`questionary`'s confirm question requires a default value](https://github.com/tmbo/questionary/blob/87a891c41a0199bb23b2b230e971fd15db32c17b/questionary/prompts/confirm.py#L22) and `False` seems better than `True` IMO.
* `choice: ...` question: "The first choice" because `questionary` doesn't support no initial choice and falls back to the first choice if no default value is provided.

For `int`/`float`/`yaml`/`json` questions, I'd initialize the input prompt empty and require a valid answer - also for `yaml` where I'd *not* treat an empty string or only spaces as `null` although `yaml.safe_load("")` behaves like that because it is inconsistent with `json` and not intuitive IMO.

That said, I don't agree with

> [...] but an empty string in the default field should not imply required=true since in some cases the default value may be an empty string.
>
> &mdash; https://github.com/copier-org/copier/issues/355#issuecomment-1019069511

because `default: ""` is a perfectly fine value or a `str` question and I see no reason why the question should ever imply `required: true` then. In fact, the presence of a `default` field implies an optional question and vice versa, so having both a `default` field and a `required` field is redundant.

WDYT?

**Comment by yajo** [comment]
> The `--defaults` flag (or equivalent argument via API) can only be used when the `default` field is set for _all_ questions. Otherwise, an error is raised. Questions without a `default` field are required and must be answered either interactively or via the `--data` flag (or equivalent argument via API).

So, `--defaults` will work as long as all questions without defaults are answered via `--data`, right?

> because `default: ""` is a perfectly fine value or a `str` question and I see no reason why it should ever imply `required: true` then. In fact, the presence of a `default` field implies an optional question and the absence of a `default` field implies a required field, so having both a `default` field and a `required` field is redundant.

I agree. For a required str question, just add `validator: '{% if not answer %}Required{% endif %}'. It's not as ergonomic, but works and is simpler to maintain upstream.

**Comment by yajo** [comment]
> for `yaml` where I'd _not_ treat an empty or spaces-only string as `null` although `yaml.safe_load("")` behaves like that because it is inconsistent with `json` and not intuitive IMO. If somebody wants to answer with `null`, then they should answer `null`.

This behavior is documented in [the YAML spec](https://yaml.org/spec/1.2.2/#72-empty-nodes), so I think we should respect the spec and let empty strings become `None` when parsed.

**Comment by sisp** [comment]
> So, `--defaults` will work as long as all questions without defaults are answered via `--data`, right?

Correct.

> This behavior is documented in [the YAML spec](https://yaml.org/spec/1.2.2/#72-empty-nodes), so I think we should respect the spec and let empty strings become `None` when parsed.

I hadn't thought about that. Right, the spec should certainly be respected. :+1:

**Comment by sisp** [comment]
I've made the changes as we discussed. Any question that has no `default` field is considered to be a required question and needs an explicit answer via interactive mode, CLI or API. When the `--defaults` flag is used, questions without a `default` field need to be answered via the `--data` flag. Note that `--defaults` implies non-interactive mode, i.e. it is not possible to interactively answer questions without a `default` field. This behavior seems consistent with the current behavior as `--defaults` for questions without a `default` field result in the answer `None`. If we want to distinguish between interactive and non-interactive mode, we might need to add another flag in a separate PR.

The implementation of this behavior requires a new value that has the semantics "not set" for the value of the `default` field when the `default` field is missing. `None` doesn't work because it might be a regular default value. Therefore, I introduced a sentinel type `MissingType` and a corresponding constant `MISSING` inspired by https://github.com/python/mypy/issues/5424#issuecomment-410866316.

A few tests require adjustment to the new behavior because they rely on the default answer to a question without a `default` field to be `None`. I've made those changes.

WDYT, @yajo?

**Review by yajo — APPROVED** [review]
Great!

**Comment by yajo** [comment]
Would you please fix the conflics to merge?

**Comment by sisp** [comment]
Done. And I've also added type hints made some minor stylistic improvements.

**Comment by sisp** [comment]
I just pushed a commit that removes obsolete special treatment of `str` questions when the answer is `None` because this isn't valid anymore.

**Pull request merged**
