### PR TITLE
Introducing Copier Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello Copier team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Copier Guru](https://gurubase.io/g/copier) to Gurubase. Copier Guru uses the data from this repo and data from the [docs](https://copier.readthedocs.io/en/stable/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Copier Guru" badge, which highlights that Copier now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Copier Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by pawamoy** [comment]
Interesting, thanks for the heads up. I asked a few questions. The results ranged from good to not bad but incomplete :slightly_smiling_face:

**Comment by kursataktas** [comment]
We have an exciting release coming up in a few days that will significantly improve answer accuracy. I would love to hear your thoughts after it's out—would that work for you?

**Review by yajo — APPROVED** [review]
Awesome! Finally we have our own assistant!



Jokes apart, it's amazing. Thanks!

**Comment by pawamoy** [comment]
> the most frequently asked ones

Nice, this would be valuable to maintainers. We can already get similar results from search engines, but I suppose questions on a service like Gurubase will be much more detailed.

**Comment by kursataktas** [comment]
Hello Everyone,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by pawamoy** [comment]
Thanks for the update @kursataktas. Quick note from myself too: I just published a new MkDocs plugin, [mkdocs-llmstxt](https://github.com/pawamoy/mkdocs-llmstxt), which allows MkDocs users to automatically generate an `/llms.txt` file in their site that can be consumed by LLM users (to add context to the model). I felt this is kinda relevant to the PR here so wanted to share :slightly_smiling_face:

**Comment by kursataktas** [comment]
This is a super interesting idea! I wish all documentation sites had something like this, it would save us tons of time and computational energy. How has the adoption been within the community? Is there anything we can do to help?

**Comment by pawamoy** [comment]
The adoption of the /llms.txt standard seems to grow nicely. My plugin is just 3 days old so probably nobody is using it yet :sweat_smile: Just spreading the word (on both the standard and MkDocs plugin) would be helpful :smile: Thanks!

**Comment by kursataktas** [comment]
Hello @pawamoy,

I want to share an exciting update about Gurubase. We've recently released several great features that I think you'll find interesting.

### 1. Slack & Discord Integration
You can now add your Guru as a bot to Slack and Discord, allowing you to ask questions instantly. More details here: [Discord Bot Integration](https://docs.gurubase.ai/integrations/discord-bot).

### 2. Analytics Dashboard
Track what your users ask your Guru and gain valuable insights. This feature is available on the "My Gurus" page. If you haven’t maintained your Guru yet, I highly recommend doing so to access your analytics. More information about claiming your Guru can be found [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).
image

### 3. API Support
All Guru functionalities are now accessible via API. You can ask questions, edit data sources, and more using our API endpoints. Here is the [API Doc](https://docs.gurubase.ai/api-reference/introduction).

### 4. Codebase Indexing
We now support indexing codebases from GitHub repositories to generate answers for related queries. This feature is available for select Gurus. If you don’t see the "Codebase Indexed" label on your Guru edit page and would like access, please let me know, I’d be happy to enable it for you!
image


Let me know if you have any questions or feedback!

**Comment by kursataktas** [comment]
Hey @pawamoy,

I wanted to update you that we’ve released the Gurubase GitHub bot!
This means you can now integrate your Guru into your repository,  so users can ask it questions directly through GitHub issues. By default, the Gurubase bot automatically responds to newly opened issues, but you can customize its behavior if needed.

You can see it in action in [this demo issue](https://github.com/Gurubase/gurubase/issues/248).
More information about the bot can be found [here](https://docs.gurubase.ai/integrations/github-bot).

gurubase-github-bot-demo

-----

_Note: As I mentioned in my first update on this thread, please let me know if you’d prefer not to receive updates here._

**Pull request merged**
