### PR TITLE
build: use poetry-dynamic-versioning wrapper for build backend

### PR DESCRIPTION
**Pull request by sisp**
I've updated the `build-backend` config in `pyproject.toml` according to the [`poetry-dynamic-versioning` installation instructions](https://github.com/mtkennerly/poetry-dynamic-versioning#installation).

### CODE REVIEW

**Comment by sisp** [comment]
Hm, now the docs build fails. :thinking:

**Comment by pawamoy** [comment]
It should be `backend` instead of `api` based on the docs you linked 🙂

**Comment by sisp** [comment]
OMG! :rofl: You're right, of course!

**Review by yajo — APPROVED** [review]
Great, thanks!

**Pull request merged**
