### PR TITLE
docs(readme): spelling

### PR DESCRIPTION
**Pull request by dafyddj**

### CODE REVIEW

**Comment by yajo** [comment]
I'm not native english, but it seems that it was correct: https://www.wordreference.com/definition/questionary

Could you explain this change a bit more, or give some docs about it please?

**Comment by dafyddj** [comment]
Screenshot 2023-11-27 at 14 53 17 copy

As a native speaker I have to say I have never heard or seen `questionary` used before and assumed it was a typo.

**Comment by sisp** [comment]
I'm no native speaker either, but my dictionary says that "questionary" is rare, more widely used seems to be "questionnaire".

https://dict.leo.org/englisch-deutsch/questionary

**Review by yajo — APPROVED** [review]
Thanks!

**Pull request merged**
