### PR TITLE
build: test and advertise Python 3.12 support

### PR DESCRIPTION
**Pull request by noirbizarre**
A basic pull request adding Python 3.12 to tested versions as well as proper PyPI classifiers for Python 3.12 support advertisement.

No functional changes

### CODE REVIEW

**Review by sisp — CHANGES_REQUESTED** [review]
Thanks for caring about this maintenance work, @noirbizarre! 🙏 

I believe you just ran `poetry lock` or `poetry update`, right? It seems only `pywin32` needed an update though. I'd prefer not mixing a complete lock file update with adding support for Python 3.12. Would you mind reverting `poetry.lock` and trying to update only `pywin32` through `poetry update pywin32`?

**Comment by sisp** [comment]
By the way, I think the tests are failing now because of the most recent mypy version. See also https://github.com/copier-org/copier/pull/1286#issuecomment-1673306751.

**Comment by noirbizarre** [comment]
Yep, exactly. PR updated with minimal lock change.
Sorry for the multiple trials, I don't have other mean to test against Windows and MacOS.

**Review by yajo — APPROVED** [review]
Thanks!

**Comment by sisp** [comment]
One CI job is failing though, I'm not quite sure why. It seems to be related to the pip vendored by Python 3.12. https://github.com/pypa/pip/issues/11501 looks like the same problem. I wonder why only the Ubuntu job is failing.

**Comment by noirbizarre** [comment]
I think `virtualenv` needed an update, so I just did `poetry update virtualenv`.
For reference, the idea comes from https://github.com/pre-commit/pre-commit/issues/3041

**Review by sisp — APPROVED** [review]
Perfect, thanks for investigating that problem! :ok_hand:

LGTM! :tada: Thanks again for engaging also in this maintenance work, much appreciated! :pray:

**Comment by noirbizarre** [comment]
I try to contribute as much as possible to tools I use, even for small tasks.
Given I contribute to those tools, I benefit too from housekeeping and maintenance.
Anyway, I'm pleased to help !

**Pull request merged**
