### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by yajo** [comment]
Woah, we accumulated a few over time! Thanks 😊

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by pawamoy** [comment]
Nice, thanks @kianmeng!

Out of curiosity, did you search for typos manually? I've recently published a spellcheck plugin for MkDocs, we could give it a try.

**Comment by kianmeng** [comment]
@pawamoy Using https://github.com/codespell-project/codespell and aspell.

I assumed is this one, https://github.com/pawamoy/mkdocs-spellcheck?

**Comment by pawamoy** [comment]
Thanks :) yup that's the one

**Pull request merged**
