### PR TITLE
refactor: drop `pyyaml-include` dependency and reimplement relevant features

### LINKED ISSUE #1398: pyyaml-include is GPL3, doesn't that poison your MIT project?
### Describe the problem

pyyaml-include, one of your dependencies, is GPL3 - doesn't that poison your MIT project?

### Template

-

### To Reproduce

_No response_

### Logs

_No response_

### Expected behavior

-

### Screenshots/screencasts/logs

_No response_

### Operating system

Windows

### Operating system distribution and version

-

### Copier version

-

### Python version

-

### Installation method

pipx+pypi

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sisp**
I've dropped the `pyyaml-include` dependency and reimplemented the features we use in Copier, which are just a subset of what `pyyaml-include` offers.

Resolves #1398.

### CODE REVIEW

**Review by pawamoy — APPROVED** [review]
Awesome!

**Review by pawamoy — APPROVED** [review]

**Comment by sisp** [comment]
@pawamoy Sorry about the frequent force-pushes. I couldn't decide on test case names ... :laughing:

**Comment by sisp** [comment]
Testing pays off ... ☝️ :laughing:

**Comment by sisp** [comment]
I think we're good now. Merging ... :rocket:

**Pull request merged**
