### PR TITLE
feat: support choice validation via extended syntax 

### LINKED ISSUE #1001: Add support for conditional choices
**Is your feature request related to a problem? Please describe.**
Sometimes, there is a dependency between questions where the validity of an answer to a choice question depends on the answer to a previous question. Currently, Copier doesn't support enforcing constraints on choice questions.

**Describe the solution you'd like**
I'd like to be able to make a choice item conditional, so that only valid choices are presented in interactive mode and an invalid answer would raise a validation error in CLI/API mode.

I believe conditional choice items could be implemented like this:

```yaml
# List syntax
question_with_list_choices:
  choices:
    - "{% if <condition-1> %}choice-1{% endif %}"
    - "{% if <condition-2> %}choice-2{% endif %}"
    - ...

# Dict syntax
question_with_dict_choices:
  choices:
    "{% if <condition-1> %}choice-1{% endif %}": null
    "{% if <condition-2> %}choice-2{% endif %}": null

# Tuple syntax
question_with_tuple_choices:
  choices:
    - ["{% if <condition-1> %}choice-1{% endif %}", null]
    - ["{% if <condition-2> %}choice-2{% endif %}": null]
```

Whenever (a) the list item is an empty string or (b) the dict key is an empty string or (c) the first element in the tuple is an empty string, the choice is ignored. Of course, a non-`null` value is possible for the dict and tuple syntax, but I wanted to keep the example consistent.

Copier currently allows an empty choice:

```yaml
question_with_list_choices:
  choices:
    - ""
```

```shell
$ copier $tpl $dst
🎤 question_with_list_choices
   (Use arrow keys)
 »
```

However, I don't think empty choices make much sense, so it should be fine to ignore them.

**Describe alternatives you've considered**
Instead of omitting invalid choices, it might be useful to show all choices and validate them, so that invalid choices show an error when selected. Regarding UX, I think omitting invalid choices is preferable to showing errors though.

**Additional context**
Related to #996.

### PR DESCRIPTION
**Pull request by sisp**
I've added support for conditional choices, i.e. choices whose validity depends on answers to previous questions.

In interactive mode, disabled choices are not shown and cannot be selected. In CLI/API mode, passing the value of a disabled choice will raise an error.

The templated prompt test case is based on the example from #996. If I understand the [compatibilities between Terraform and Terragrunt versions](https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/) right, these versions should be compatible:

<table>
<tr>
<td colspan="2" rowspan="2"></td>
<th colspan="4">Terragrunt</th>
</tr>
<tr>
<td>0.38</td>
<td>0.39</td>
<td>0.40</td>
<td>0.41</td>
</tr>
<tr>
<th rowspan="2">Terraform</th>
<td>1.2</td>
<td>:heavy_check_mark:</td>
<td>:heavy_check_mark:</td>
<td>:heavy_check_mark:</td>
<td>:heavy_check_mark:</td>
</tr>
<tr>
<td>1.3</td>
<td></td>
<td></td>
<td>:heavy_check_mark:</td>
<td>:heavy_check_mark:</td>
</tr>
</table>

Closes #1001. Related to #996.

/cc @verdaatt

### CODE REVIEW

**Review by yajo — CHANGES_REQUESTED** [review]
Please could you implement this design instead? https://github.com/copier-org/copier/issues/1001#issuecomment-1464842885

**Comment by sisp** [comment]
I've changed the implementation to use the extended syntax we discussed. I've also updated the example and test case to a cloud & IaC tool questionnaire because I found it more intuitive and easier to grasp.

One test is failing now because this PR requires #1111 to be merged first.

**Comment by sisp** [comment]
#1111 has been merged and I've pulled the latest state of `master`. The tests are passing now, I think this PR is ready for a review. :pray:

**Review by yajo — APPROVED** [review]
Code looks OK, thanks!

I still have to do the functional review.

**Pull request merged**
