### PR TITLE
chore: Use pyclean to reduce custom developer tooling

### PR DESCRIPTION
**Pull request by bittner**
Reduces the code in the `devtasks` module replacing cleanup activity code by integrating [pyclean](https://pypi.org/project/pyclean/) in the development toolchain. PyClean is a tool focused on cleaning up Python bytecode and build artifacts.

<details>
<summary>`poetry install --with dev` (click to show output)</summary>

```console
$ poetry install --with dev
Installing dependencies from lock file

Package operations: 33 installs, 0 updates, 0 removals

  - Installing distlib (0.3.7)
  - Installing exceptiongroup (1.1.0)
  - Installing filelock (3.13.0)
  - Installing iniconfig (2.0.0)
  - Installing platformdirs (3.11.0)
  - Installing pluggy (1.5.0)
  - Installing setuptools (68.1.2)
  - Installing tomli (2.0.1)
  - Installing cfgv (3.3.1)
  - Installing coverage (7.0.5)
  - Installing execnet (2.1.1)
  - Installing identify (2.5.13)
  - Installing mypy-extensions (1.0.0)
  - Installing nodeenv (1.7.0)
  - Installing pastel (0.2.1)
  - Installing ptyprocess (0.7.0)
  - Installing pytest (8.2.2)
  - Installing types-docutils (0.20.0.20240317)
  - Installing types-setuptools (69.2.0.20240317)
  - Installing virtualenv (20.24.6)
  - Installing mypy (1.10.0)
  - Installing pexpect (4.9.0)
  - Installing poethepoet (0.26.1)
  - Installing pre-commit (3.5.0)
  - Installing pyclean (3.0.0)
  - Installing pytest-cov (5.0.0)
  - Installing pytest-gitconfig (0.6.0)
  - Installing pytest-xdist (3.6.1)
  - Installing types-backports (0.1.3)
  - Installing types-colorama (0.4.15.20240311)
  - Installing types-psutil (6.0.0.20240621)
  - Installing types-pygments (2.18.0.20240506)
  - Installing types-pyyaml (6.0.12.20240311)

Installing the current project: copier (0.0.0)
```

</details>

<details>
<summary>`poe clean` (click to show output)</summary>

```console
$ poe clean
Poe => pyclean . --debris --verbose
Debris topics to scan for: cache coverage package pytest ruff
Ignored directories: .git .hg .svn .tox .venv node_modules venv
Cleaning directory .
Skipping .git
Scanning for debris of Cache ...
Scanning for debris of Coverage ...
Scanning for debris of Package ...
Scanning for debris of Pytest ...
Scanning for debris of Ruff ...
Total 0 files, 0 directories removed.
```

</details>

Closes: #1669

### CODE REVIEW

**Comment by bittner** [comment]
Nix is a beast!—How can I add `setuptools` to the Python setup, so that PyClean installs successfully? Pytest also relies on setuptools and it installs fine. Why is this so hard to get it right?

Do I _have_ to add a dedicated package definition to the [development/python-modules](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/python-modules) pkgs of the nixpkgs repository?

**Review by yajo — CHANGES_REQUESTED** [review]
Personally i never used this task. Could you just remove it?

**Comment by bittner** [comment]
> Personally i never used this task. Could you just remove it?

Depending on what your personal relationship is to debris polluting your project workspace, it certainly makes sense to have a cleanup job at hand. Most people love a cleaned-up kitchen.—Maybe give it a try?

**Comment by yajo** [comment]
I think it is better to remove it. Anybody that wants to use it can simply install and run pyclean AFAICS. You can mention it in the contributing guide if you want!

**Comment by pawamoy** [comment]
> Anybody that wants to use it can simply install and run pyclean AFAICS

```
pipx run pyclean . --debris --verbose
```

:+1:

**Comment by bittner** [comment]
I incorporated the changes as requested. I also rebased the PR. Checks are green, ready for merging. :rocket:

**Review by yajo — APPROVED** [review]

**Pull request merged**
